version: '3.8'

services:
  # -----------------------------
  # HDFS - NameNode
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./namenode-entrypoint.sh:/namenode-entrypoint.sh:ro
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    ports:
      - "9870:9870"   # Web UI
      - "9000:9000"   # HDFS RPC
      - "8020:8020"
    entrypoint: [ "/namenode-entrypoint.sh" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - hadoop-net

  # -----------------------------
  # HDFS - DataNode
  # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/datanode:/hadoop/dfs/data
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - hadoop-net

  # -----------------------------
  # PostgreSQL for Hive Metastore
  # -----------------------------
  hive-metastore-postgresql:
    image: postgres:13
    container_name: hive-metastore-postgresql
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # Hive Metastore
  # -----------------------------
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - HIVE_METASTORE_DB_HOST=hive-metastore-postgresql
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
    volumes:
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
      - ./wait-for-it.sh:/wait-for-it.sh:ro
    entrypoint: [ "/wait-for-it.sh", "hive-metastore-postgresql", "5432", "--", "/opt/hive/bin/hive", "--service", "metastore" ]
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
      hive-metastore-postgresql:
        condition: service_healthy
    ports:
      - "9083:9083"
    networks:
      - hadoop-net


  # -----------------------------
  # HiveServer2
  # -----------------------------
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    volumes:
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
      - ./wait-for-it.sh:/wait-for-it.sh:ro
    entrypoint: [ "/wait-for-it.sh", "hive-metastore", "9083", "--", "/opt/hive/bin/hiveserver2" ]
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
      hive-metastore:
        condition: service_started
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - hadoop-net

volumes:
  namenode-data:
  datanode-data:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge
