version: '3.8'

services:
  #########################################
  # 1. Hive Metastore Database (PostgreSQL)
  #########################################
  postgres-metastore:
    image: postgres:12
    container_name: postgres-metastore
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/metastore_db:/var/lib/postgresql/data
    networks:
      - hadoop-hive-net

  #########################################
  # 2. Hadoop Cluster (HDFS + YARN)
  #########################################
  namenode:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hadoop-namenode:hadoop3.3.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS Port
    volumes:
      - ./data/hadoop/namenode:/hadoop/dfs/name
    networks:
      - hadoop-hive-net

  datanode:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hadoop-datanode:hadoop3.3.4-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./data/hadoop/datanode:/hadoop/dfs/data
    networks:
      - hadoop-hive-net

  resourcemanager:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hadoop-resourcemanager:hadoop3.3.4-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "8088:8088"  # YARN Web UI
    networks:
      - hadoop-hive-net

  nodemanager:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hadoop-nodemanager:hadoop3.3.4-java8
    container_name: nodemanager
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop-hive-net

  #########################################
  # 3. Hive Services
  #########################################
  hive-metastore:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hive-metastore:hive3.1.3-java8
    container_name: hive-metastore
    depends_on:
      - namenode
      - postgres-metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9870 postgres-metastore:5432
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - METASTORE_DB_HOSTNAME=postgres-metastore
      - METASTORE_DB_NAME=metastore
      - METASTORE_DB_USER=hive
      - METASTORE_DB_PASSWORD=hive
    networks:
      - hadoop-hive-net

  hive-server:
    # UPDATED TAG: Removed '2.0.0-' prefix
    image: bde2020/hive-server:hive3.1.3-java8
    container_name: hive-server
    depends_on:
      - namenode
      - hive-metastore
      - resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 hive-metastore:9083 resourcemanager:8088
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HIVE_METASTORE_URIS=thrift://hive-metastore:9083
    ports:
      - "10000:10000" # HiveServer2 Thrift port
      - "10002:10002" # HiveServer2 Web UI
    networks:
      - hadoop-hive-net

volumes:
  data:

networks:
  hadoop-hive-net: