version: '3.8'

services:
  # -----------------------------
  # HDFS NameNode
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8020:8020"
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # HDFS DataNode
  # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/datanode:/hadoop/dfs/data
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # Hive Metastore PostgreSQL
  # -----------------------------
  hive-metastore-postgresql:
    image: postgres:14
    container_name: hive-metastore-postgresql
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 5s
      retries: 20

  # -----------------------------
  # Hive Metastore (auto-initializes schema)
  # -----------------------------
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-metastore
    platform: linux/amd64
    env_file:
      - ./hadoop.env
    depends_on:
      hive-metastore-postgresql:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Waiting for PostgreSQL...';
      until pg_isready -h hive-metastore-postgresql -p 5432 -U $HIVE_METASTORE_USER; do
          sleep 2;
      done;
      echo 'PostgreSQL ready. Initializing schema...';
      schematool -dbType postgres -initSchema;
      echo 'Starting Hive Metastore...';
      /opt/hive/bin/hive --service metastore
      "
    ports:
      - "9083:9083"
    networks:
      - hadoop-net


  # -----------------------------
  # HiveServer2
  # -----------------------------
  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-server
    platform: linux/amd64
    env_file:
      - ./hadoop.env
    depends_on:
      - hive-metastore
    volumes:
      - /home/iitgcpuser/iit/lab5/hadoop-hive-dockercompose/recharge.input:/opt/recharge.input
    ports:
      - "10000:10000"
    networks:
      - hadoop-net

volumes:
  namenode-data:
  datanode-data:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge
