version: '3.8'

services:
  # -----------------------------
  # HDFS - NameNode
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:8020
    volumes:
      - ./data_new/namenode:/hadoop/dfs/name
#      - ./hadoop_dir:/opt/hadoop-2.7.4/etc/hadoop        # <-- FIXED PATH
    ports:
      - "50070:50070"                                     # <-- FIXED PORT
      - "8020:8020"
    networks:
      - hadoop-net
    healthcheck:
      test: [ "CMD", "hdfs", "dfsadmin", "-report" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # HDFS - DataNode
  # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8  # <-- FIXED IMAGE
    container_name: datanode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:8020
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:8020
    volumes:
      - ./data_new/datanode:/hadoop/dfs/data
#      - ./hadoop_dir:/opt/hadoop-2.7.4/etc/hadoop        # <-- FIXED PATH
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net

  # -----------------------------
  # PostgreSQL for Hive Metastore
  # -----------------------------
  hive-metastore-postgresql:
    image: postgres:12
    container_name: hive-metastore-postgresql
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore-db:/var/lib/postgresql/data
#      - ./init-metastore.sql:/docker-entrypoint-initdb.d/init-metastore.sql
    ports:
      - "5432:5432"
    networks:
      - hadoop-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hive" ]
      interval: 5s
      retries: 20
      timeout: 5s
#    command: ["postgres", "-c", "password_encryption=md5"]

  # -----------------------------
  # Hive Metastore
  # -----------------------------
  hive-metastore-init:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-metastore-init
    env_file:
      - ./hadoop.env
    depends_on:
      hive-metastore-postgresql:
        condition: service_healthy
      namenode:
        condition: service_healthy
    command: [ "schematool", "-dbType", "postgres", "-initSchema", "-verbose" ] # <-- FIX HERE
    networks:
      - hadoop-net
  

  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    depends_on:
      hive-metastore-init:
        condition: service_completed_successfully
    command: >
      bash -c "
      echo 'Starting Hive Metastore...';
      exec /opt/hive/bin/hive --service metastore
      "
    ports:
      - "9083:9083"
    networks:
      - hadoop-net


  # -----------------------------
  # HiveServer2
  # -----------------------------
  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-server
    platform: linux/amd64
    env_file:
      - ./hadoop.env
    depends_on:
      hive-metastore:
        condition: service_healthy
      namenode: # <-- ADD THIS DEPENDENCY
        condition: service_healthy
    ports:
      - "10000:10000"
    networks:
      - hadoop-net

volumes:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge
