version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.1-java8
    container_name: namenode
    platform: linux/amd64
    volumes:
      -./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      -./hadoop-hive.env
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.1-java8
    container_name: datanode
    platform: linux/amd64
    depends_on:
      - namenode
    volumes:
      -./data/datanode:/hadoop/dfs/data
    env_file:
      -./hadoop-hive.env
    ports:
      - "9864:9864"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.1-java8
    container_name: resourcemanager
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
    env_file:
      -./hadoop-hive.env
    ports:
      - "8088:8088"

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.1-java8
    container_name: nodemanager
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    env_file:
      -./hadoop-hive.env

  hive-server:
    image: bde2020/hive:2.3.2-spark-2.2.0
    container_name: hive-server
    platform: linux/amd64
    depends_on:
      - hive-metastore
      - resourcemanager
    env_file:
      -./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql/metastore"
      - "SERVICE_PRECONDITION=hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"

  hive-metastore:
    image: bde2020/hive:2.3.2-spark-2.2.0
    container_name: hive-metastore
    platform: linux/amd64
    depends_on:
      - hive-metastore-postgresql
    env_file:
      -./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    platform: linux/amd64
    volumes:
      -./data/metastore_db:/var/lib/postgresql/data
    env_file:
      -./hadoop-hive.env