version: '3.8'

services:
  #########################################
  # 1. Hive Metastore Database (PostgreSQL)
  #########################################
  postgres-metastore:
    image: postgres:12
    container_name: postgres-metastore
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "5432:5432"
    volumes:
      - metastore-db-data:/var/lib/postgresql/data
    networks:
      - hadoop-hive-net

  #########################################
  # 2. Hadoop Cluster (All-in-one)
  #########################################
  hadoop:
    image: bitnami/hadoop:3.3.6
    container_name: hadoop
    environment:
      # Enable HDFS and YARN
      - HADOOP_DEFAULTS_HDFS_ENABLE=true
      - HADOOP_DEFAULTS_YARN_ENABLE=true
      # Format HDFS on first run
      - HADOOP_HDFS_FORMAT=true
    ports:
      - "9870:9870"  # NameNode Web UI
      - "8088:8088"  # YARN Web UI
    volumes:
      - hadoop-data:/opt/bitnami/hadoop/data
    networks:
      - hadoop-hive-net

  #########################################
  # 3. Hive Services (using Bitnami images)
  #########################################
  hive-metastore:
    image: bitnami/hive:3.1.3
    container_name: hive-metastore
    depends_on:
      - postgres-metastore
      - hadoop
    environment:
      - HIVE_ROLE=metastore
      # Postgres Metastore Config
      - HIVE_METASTORE_DATABASE_HOST=postgres-metastore
      - HIVE_METASTORE_DATABASE_NAME=metastore
      - HIVE_METASTORE_DATABASE_USER=hive
      - HIVE_METASTORE_DATABASE_PASSWORD=hive
      # Link to Hadoop
      - HADOOP_HOST=hadoop
    networks:
      - hadoop-hive-net

  hive-server:
    image: bitnami/hive:3.1.3
    container_name: hive-server
    depends_on:
      - hive-metastore
      - hadoop
    environment:
      - HIVE_ROLE=hiveserver2
      # Link to the Metastore service
      - HIVE_METASTORE_URIS=thrift://hive-metastore:9083
      # Link to Hadoop
      - HADOOP_HOST=hadoop
    ports:
      - "10000:10000" # HiveServer2 Thrift port
      - "10002:10002" # HiveServer2 Web UI
    networks:
      - hadoop-hive-net

volumes:
  metastore-db-data:
  hadoop-data:

networks:
  hadoop-hive-net: