version: '3.8'

services:
  # -----------------------------
  # HDFS - NameNode
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./namenode-entrypoint.sh:/namenode-entrypoint.sh:ro
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    ports:
      - "9870:9870"   # Web UI
      - "9000:9000"   # HDFS RPC
    entrypoint: [ "/namenode-entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9870" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - hadoop-net

    # -----------------------------
    # HDFS - DataNode
    # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - datanode-data:/hadoop/dfs/data
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - hadoop-net

  # -----------------------------
  # PostgreSQL for Hive Metastore
  # -----------------------------
  hive-metastore-postgresql:
    image: postgres:13
    container_name: hive-metastore-postgresql
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hadoop-net

  # -----------------------------
  # Hive Metastore
  # -----------------------------
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    environment:
      - HIVE_METASTORE_DB_HOST=hive-metastore-postgresql
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 hive-metastore-postgresql:5432
    ports:
      - "9083:9083"
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
      hive-metastore-postgresql:
        condition: service_started
    networks:
      - hadoop-net

  # -----------------------------
  # HiveServer2
  # -----------------------------
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 hive-metastore:9083
    ports:
      - "10000:10000"  # JDBC
      - "10002:10002"  # Web UI
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
      hive-metastore:
        condition: service_started
    networks:
      - hadoop-net

volumes:
  namenode-data:
  datanode-data:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge
