version: '3.8'

services:
  # -----------------------------
  # HDFS - NameNode
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8020:8020"
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # HDFS - DataNode
  # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:9000
    volumes:
      - ./data/datanode:/hadoop/dfs/data
      - ./hadoop_dir:/opt/hadoop-3.2.1/etc/hadoop
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 10s
      timeout: 5s
      retries: 20
  hive-metastore-init:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore-init
    env_file:
      - ./hadoop.env
    depends_on:
      - hive-metastore-postgresql
    command: >
      /opt/hive/bin/schematool -dbType postgres -initSchema

  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    volumes:
      - /home/iitgcpuser/iit/lab5/hadoop-hive-dockercompose/recharge.input:/opt/recharge.input
    container_name: hive-server
    env_file:
      - ./hadoop.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    platform: linux/amd64

volumes:
  namenode-data:
  datanode-data:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge
