version: '3.8'

services:
  # -----------------------------
  # HDFS - NameNode (Hadoop 2.7.4)
  # -----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:8020
    volumes:
      - ./data_new/namenode:/hadoop/dfs/name
    ports:
      - "50070:50070"
      - "8020:8020"
    networks:
      - hadoop-net
    healthcheck:
      test: [ "CMD", "hdfs", "dfsadmin", "-report" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # -----------------------------
  # HDFS - DataNode (Hadoop 2.7.4)
  # -----------------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:8020
      - HDFS_NAMENODE_RPC_ADDRESS=namenode:8020
    volumes:
      - ./data_new/datanode:/hadoop/dfs/data
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net

  # -----------------------------
  # PostgreSQL for Hive Metastore
  # -----------------------------
  hive-metastore-postgresql:
    image: postgres:12
    container_name: hive-metastore-postgresql
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hadoop-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hive" ]
      interval: 5s
      retries: 20
      timeout: 5s

  # -----------------------------
  # Hive Metastore Schema Initialization
  # -----------------------------
  hive-metastore-init:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore-init
    # Removed env_file to prevent HDFS configuration conflict
    environment: # <-- FINAL CORRECT ENVIRONMENT VARIABLES
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_SITE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse
    depends_on:
      hive-metastore-postgresql:
        condition: service_healthy
      namenode:
        condition: service_healthy
    command: [ "schematool", "-dbType", "postgres", "-initSchema", "-verbose" ]
    networks:
      - hadoop-net


  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    # Removed env_file to prevent HDFS configuration conflict
    environment: # <-- FINAL CORRECT ENVIRONMENT VARIABLES
      # HDFS CONFIGURATION FOR HIVE CLIENT: MUST BE EXPLICITLY DEFINED
      - HIVE_SITE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_SITE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse

      # METASTORE DB CONFIGURATION
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083

    depends_on:
      hive-metastore-init:
        condition: service_completed_successfully
      namenode:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Waiting 30 seconds for HDFS to stabilize...';
      sleep 30;
      echo 'Starting Hive Metastore...';
      exec /opt/hive/bin/hive --service metastore
      "
    ports:
      - "9083:9083"
    networks:
      - hadoop-net


  # -----------------------------
  # HiveServer2
  # -----------------------------
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    platform: linux/amd64
    # Removed env_file to prevent HDFS configuration conflict
    environment: # <-- FINAL CORRECT ENVIRONMENT VARIABLES
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_SITE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      hive-metastore:
        condition: service_started
      namenode:
        condition: service_healthy
    command: >
      bash -c "/usr/local/bin/wait-for-it.sh hive-metastore 9083 -- /opt/hive/bin/hiveserver2"
    ports:
      - "10000:10000"
    networks:
      - hadoop-net

volumes:
  metastore-db:

networks:
  hadoop-net:
    driver: bridge